using System.Text;

namespace ZMS.Application.EnvironmentBridge;

public sealed class DocumentationGenerator : IDocumentationGenerator
{
    public string GenerateReadme(EnvironmentConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# zettalogixmigrationsuite SharePoint Online Environment Automation Package");
        builder.AppendLine();
        builder.AppendLine("## Purpose");
        builder.AppendLine("This package was generated by zettalogixmigrationsuite to create a SharePoint Online enterprise test environment from a validated EnvironmentConfig JSON file.");
        builder.AppendLine();
        builder.AppendLine("## Environment");
        builder.AppendLine($"- Tenant: {config.TenantName}");
        builder.AppendLine($"- Admin URL: {config.AdminUrl}");
        builder.AppendLine($"- Root URL: {config.RootUrl}");
        builder.AppendLine($"- Owner: {config.OwnerEmail}");
        builder.AppendLine($"- Site collections: {config.SiteCollections.Count}");
        builder.AppendLine();
        builder.AppendLine("## Prerequisites");
        builder.AppendLine("- PowerShell 7 or newer");
        builder.AppendLine("- PnP.PowerShell module");
        builder.AppendLine("- SharePoint Administrator or Global Administrator role");
        builder.AppendLine("- Microsoft Entra app registration with Sites.ReadWrite.All and Files.ReadWrite.All if using app-only auth");
        builder.AppendLine();
        builder.AppendLine("## Required Microsoft Permissions");
        builder.AppendLine("- Sites.ReadWrite.All");
        builder.AppendLine("- Files.ReadWrite.All");
        builder.AppendLine("- For read-only discovery only, use read permissions such as Sites.Read.All where your tenant policy allows it.");
        builder.AppendLine("- Group.Read.All, if group validation is added later");
        builder.AppendLine();
        builder.AppendLine("## Update Config Values");
        builder.AppendLine("Edit `config/zms-spo-environment.json` before execution. Replace `clientIdPlaceholder` with your approved PnP/Entra app client ID. Do not add client secrets to this file.");
        builder.AppendLine();
        builder.AppendLine("## Run Scripts In Order");
        builder.AppendLine("```powershell");
        builder.AppendLine("pwsh ./scripts/08-Run-Preflight.ps1");
        builder.AppendLine("pwsh ./scripts/09-Run-DryRun.ps1");
        builder.AppendLine("# Only after admin review and approval:");
        builder.AppendLine("pwsh ./scripts/10-Run-All-Safe.ps1 -ClientId \"YOUR-PNP-APP-CLIENT-ID\"");
        builder.AppendLine("```");
        builder.AppendLine();
        builder.AppendLine("Only run real execution in a test tenant or approved SharePoint environment. The real execution orchestrator requires the exact confirmation string `CREATE ZMS TEST ENVIRONMENT`.");
        builder.AppendLine();
        builder.AppendLine("## Script Summary");
        builder.AppendLine("- `00-Check-Prerequisites.ps1`: Checks PowerShell, PnP.PowerShell, config file, and required permissions.");
        builder.AppendLine("- `01-Create-SiteCollections.ps1`: Creates modern TeamSiteWithoutMicrosoft365Group site collections.");
        builder.AppendLine("- `02-Create-Subsites.ps1`: Creates configured subsites where tenant settings allow them.");
        builder.AppendLine("- `03-Create-Libraries-Lists-Metadata.ps1`: Creates libraries, lists, and metadata fields.");
        builder.AppendLine("- `04-Create-Groups-Permissions.ps1`: Creates groups and applies configured permission rules.");
        builder.AppendLine("- `05-Create-Folders-And-SampleFiles.ps1`: Creates folder structures and uploads placeholder files.");
        builder.AppendLine("- `06-Apply-Migration-EdgeCases.ps1`: Applies edge-case structures for testing migration behavior.");
        builder.AppendLine("- `07-Generate-InventoryReport.ps1`: Generates local CSV/JSON inventory summaries.");
        builder.AppendLine("- `08-Run-Preflight.ps1`: Runs safe package and config checks without tenant changes.");
        builder.AppendLine("- `09-Run-DryRun.ps1`: Runs scripts 01-06 with `-DryRun` and writes a dry-run report.");
        builder.AppendLine("- `10-Run-All-Safe.ps1`: Runs real creation in safe order only after explicit confirmation.");
        builder.AppendLine("- `11-Run-Discovery-ReadOnly.ps1`: Runs live SharePoint discovery and exports JSON/CSV without changing tenant content.");
        builder.AppendLine();
        builder.AppendLine("## Read-Only Discovery After Environment Creation");
        builder.AppendLine("After preflight, dry-run, and approved environment creation, run discovery and import the output into ZMS:");
        builder.AppendLine();
        builder.AppendLine("```powershell");
        builder.AppendLine("pwsh ./scripts/11-Run-Discovery-ReadOnly.ps1 `");
        builder.AppendLine("  -ConfigPath \"./config/zms-spo-environment.json\" `");
        builder.AppendLine("  -ClientId \"YOUR-PNP-APP-CLIENT-ID\" `");
        builder.AppendLine("  -OutputPath \"./discovery-output\" `");
        builder.AppendLine("  -IncludeFiles `");
        builder.AppendLine("  -IncludePermissions `");
        builder.AppendLine("  -IncludeMetadata `");
        builder.AppendLine("  -IncludeSubsites `");
        builder.AppendLine("  -VerboseLogging");
        builder.AppendLine("```");
        builder.AppendLine();
        builder.AppendLine("Upload `discovery-output/scan-result.json` in the ZMS Discovery Center.");
        builder.AppendLine();
        builder.AppendLine("## Expected Output");
        builder.AppendLine("A SharePoint Online test tenant structure with site collections, subsites, libraries, lists, metadata, permissions, folder structures, sample files, and migration edge cases.");
        builder.AppendLine();
        builder.AppendLine("## Troubleshooting");
        builder.AppendLine("- If `Connect-PnPOnline` fails, verify the client ID and admin consent.");
        builder.AppendLine("- If subsite creation fails, tenant subsite creation may be disabled.");
        builder.AppendLine("- If permissions fail, verify group names and site ownership.");
        builder.AppendLine("- If files fail to upload, verify library creation completed.");
        builder.AppendLine();
        builder.AppendLine("## Safety Notes");
        builder.AppendLine("This API only generates files. It does not execute PowerShell or change SharePoint tenants. Review scripts before running.");
        builder.AppendLine("The generated scripts do not delete tenant content, skip existing objects, and write status to `execution/execution-status.json`.");
        return builder.ToString();
    }

    public IReadOnlyDictionary<string, string> GenerateDocumentation(EnvironmentConfig config)
    {
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["docs/architecture-overview.md"] = GenerateArchitectureOverview(config),
            ["docs/permission-model.md"] = GeneratePermissionModel(config),
            ["docs/metadata-model.md"] = GenerateMetadataModel(config),
            ["docs/migration-test-scenarios.md"] = GenerateMigrationScenarios(config)
        };
    }

    private static string GenerateArchitectureOverview(EnvironmentConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Architecture Overview");
        builder.AppendLine();
        builder.AppendLine("This environment simulates an enterprise SharePoint Online information architecture across departments.");
        builder.AppendLine();
        foreach (var site in config.SiteCollections)
        {
            builder.AppendLine($"## {site.Title}");
            builder.AppendLine($"- Department: {site.Department}");
            builder.AppendLine($"- URL: {site.Url}");
            builder.AppendLine($"- Purpose: {site.Description}");
            builder.AppendLine("- Subsites:");
            foreach (var subsite in site.Subsites)
            {
                builder.AppendLine($"  - {subsite.Title}");
            }
            builder.AppendLine();
        }

        return builder.ToString();
    }

    private static string GeneratePermissionModel(EnvironmentConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Permission Model");
        builder.AppendLine();
        builder.AppendLine("This model includes default groups, restricted areas, and broken inheritance examples for migration testing.");
        foreach (var site in config.SiteCollections)
        {
            builder.AppendLine();
            builder.AppendLine($"## {site.Title}");
            builder.AppendLine("### Groups");
            foreach (var group in site.PermissionGroups)
            {
                builder.AppendLine($"- {group.Name}: {group.Role}");
            }
            builder.AppendLine("### Restricted / Broken Inheritance Areas");
            foreach (var rule in site.PermissionRules)
            {
                builder.AppendLine($"- {rule.TargetPath}: {rule.Inheritance}. {rule.Notes}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("Migration risk increases where inheritance is broken, external users exist, or target group mapping is incomplete.");
        return builder.ToString();
    }

    private static string GenerateMetadataModel(EnvironmentConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Metadata Model");
        builder.AppendLine();
        builder.AppendLine("Metadata supports filtering, search, retention, reporting, and post-migration validation.");
        foreach (var site in config.SiteCollections)
        {
            builder.AppendLine();
            builder.AppendLine($"## {site.Title}");
            foreach (var field in site.MetadataFields)
            {
                builder.AppendLine($"- {field.Name} ({field.Type}) Required: {field.Required}");
            }
        }

        return builder.ToString();
    }

    private static string GenerateMigrationScenarios(EnvironmentConfig config)
    {
        var scenarios = new[]
        {
            "Discover site collections",
            "Discover subsites",
            "Scan libraries",
            "Scan lists",
            "Detect metadata",
            "Detect broken permissions",
            "Detect long paths",
            "Detect duplicate content",
            "Detect archived content",
            "Generate readiness report"
        };

        var builder = new StringBuilder();
        builder.AppendLine("# Migration Test Scenarios");
        builder.AppendLine();
        foreach (var scenario in scenarios)
        {
            builder.AppendLine($"- {scenario}");
        }
        builder.AppendLine();
        builder.AppendLine($"The generated environment contains {config.SiteCollections.Sum(site => site.EdgeCases.Count)} edge cases across {config.SiteCollections.Count} site collections.");
        return builder.ToString();
    }
}
